[package]
name = "chibicc_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
do-notation = "0.1.3"
# inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm18-0"] }